name: Tests

on:
  push:

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Pest on PHP ${{ matrix.php }} - Testbench ${{ matrix.testbench }}
    strategy:
      matrix:
        php: ['8.2']
        testbench: [7.*, 8.*]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          extensions: oauth
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        run: |
            composer require "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
            composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Test php code
        run: composer test:unit
